### ISSUE TITLE
Write javadocs for all implemented classes

### ISSUE THREAD

**Issue by BHolmwood** [CMPUT301F14T04/Funtime-Runtime-Project#68]

**Comment by BHolmwood** [comment]
Finished Account, ApplicationState, CreateAccountActivity, LoginActivity, CustomActivity, MyFavouritesActivity, ReadingListActivity

**Comment by pranner** [comment]
Finished MyQuestionsActivity

**Comment by pranner** [comment]
Finished Question and Answer model classes

**Comment by scherfan** [comment]
Finished MyHistory and HomeActivity

**Comment by pranner** [comment]
Javadocs for all classes completed.
